Repository sam-tripathi/Defeat-JAVA, pull requests merged in 2022-10, with the labels that each got.

#4 Create problem
  PROBLEMS/searching_problems
  SOLUTIONS/searching_problems_solutions
Labels: non code contribution

#31 Create DSA-Beginners resource guide
  DSA-Beginners resource guide
Labels: documentation, non code contribution, great-job

#29 Learn Java from Free Resources
  EXTERNAL RESOURCES FOR JAVA.md
Labels: documentation, Hacktoberfest, non code contribution

#33 Added BMI Calculator
  SIMPLE PROJECTS/BMI Calculator/main.java
Labels: Hacktoberfest, great-job

#35 feat: add simple java spring security project
  SIMPLE PROJECTS/spring sec/Security/SecurityConf.java
  SIMPLE PROJECTS/spring sec/controller/Users/Roles_Controller.java
  SIMPLE PROJECTS/spring sec/controller/Users/Users_Controller.java
  SIMPLE PROJECTS/spring sec/model/Users/Roles.java
  SIMPLE PROJECTS/spring sec/model/Users/Users.java
  SIMPLE PROJECTS/spring sec/repository/Users/Role_Repository.java
  SIMPLE PROJECTS/spring sec/repository/Users/Users_Repository.java
  SIMPLE PROJECTS/spring sec/serivice/Users/RoleService.java
  SIMPLE PROJECTS/spring sec/serivice/Users/UserDetailsPrincipal.java
  SIMPLE PROJECTS/spring sec/serivice/Users/UserService.java
Labels: good first issue, Hacktoberfest

#27 Data Structures and Problems in Java
  DataStructures/LinkedList.java
  DataStructures/SpiralMatrix.java
  DataStructures/Stacks.java
  DataStructures/frequencyOfElementsInArrayHash.java
Labels: Hacktoberfest, great-job

#36 Issue:15 Added Sudoku Solver with GUI
  SIMPLE PROJECTS/SpringSample/target/classes/application.properties
  SIMPLE PROJECTS/SpringSample/target/classes/com/basak/SpringSample/SpringSampleApplication.class
  SIMPLE PROJECTS/SpringSample/target/classes/com/basak/SpringSample/student/Student.class
  SIMPLE PROJECTS/SpringSample/target/classes/com/basak/SpringSample/student/StudentConfig.class
  SIMPLE PROJECTS/SpringSample/target/classes/com/basak/SpringSample/student/StudentController.class
  SIMPLE PROJECTS/SpringSample/target/classes/com/basak/SpringSample/student/StudentRepository.class
  SIMPLE PROJECTS/SpringSample/target/classes/com/basak/SpringSample/student/StudentService.class
  SIMPLE PROJECTS/SpringSample/target/test-classes/com/basak/SpringSample/SpringSampleApplicationTests.class
  SIMPLE PROJECTS/SudokuSolverGUI/Description.txt
  SIMPLE PROJECTS/SudokuSolverGUI/GUI.java
  SIMPLE PROJECTS/SudokuSolverGUI/Solver.java
  SIMPLE PROJECTS/SudokuSolverGUI/SudokuClass.java
Labels: Hacktoberfest, HACKTOBERFEST-ACCEPTED, great-job

#41 Added some Beginner Programs in JAVA
  SIMPLE PROJECTS/Beginner Java/BinarySearch.java
  SIMPLE PROJECTS/Beginner Java/BubbleSort.java
  SIMPLE PROJECTS/Beginner Java/Factorial_ofnumber.java
  SIMPLE PROJECTS/Beginner Java/Fibonacci_series.java
  SIMPLE PROJECTS/Beginner Java/InsertionSort.java
  SIMPLE PROJECTS/Beginner Java/Is_Armstrong.java
  SIMPLE PROJECTS/Beginner Java/Is_Pallindrome.java
  SIMPLE PROJECTS/Beginner Java/LinearSearch.java
  SIMPLE PROJECTS/Beginner Java/PrimeNumber.java
  SIMPLE PROJECTS/Beginner Java/SelectionSort.java
Labels: Hacktoberfest, HACKTOBERFEST-ACCEPTED, great-job

#44 Add files via upload
  SOLUTIONS/ABOVEAVG.java
  SOLUTIONS/ADVANCE.java
  SOLUTIONS/AGELIMIT.java
  SOLUTIONS/ALTER.java
  SOLUTIONS/AMR15A.java
  SOLUTIONS/ANTI_PAL.java
  SOLUTIONS/ARRAYBREAK.java
  SOLUTIONS/AVOIDCONTACT.java
  SOLUTIONS/BADMINTON.java
  SOLUTIONS/BINBASBASIC.java
  SOLUTIONS/BITBLEND.java
  SOLUTIONS/BOBBANK.java
  SOLUTIONS/BREAKSTICK.java
  SOLUTIONS/BSCOST.java
  SOLUTIONS/CHEFBARBER.java
  SOLUTIONS/CHEFGAMES.java
  SOLUTIONS/CHEFONDATE.java
  SOLUTIONS/CHEFRACES.java
  SOLUTIONS/CHESSTIME.java
  SOLUTIONS/CIELRCPT.java
  SOLUTIONS/COLOUR.java
  SOLUTIONS/CONN.java
  SOLUTIONS/COPYPUSH.java
  SOLUTIONS/COVID_19.java
  SOLUTIONS/CRYCOLR.java
  SOLUTIONS/CWIREFRAME.java
  SOLUTIONS/DETSCORE.java
  SOLUTIONS/DIV3.java
  SOLUTIONS/DOLL.java
  SOLUTIONS/EANDO.java
  SOLUTIONS/ENDSORTED.java
  SOLUTIONS/EQBYXOR.java
  SOLUTIONS/EQDIS.java
  SOLUTIONS/EQPAIR.java
  SOLUTIONS/EQUALDIST.java
  SOLUTIONS/EQUIVALENT.java
  SOLUTIONS/EUREKA.java
  SOLUTIONS/EVMHACK.java
  SOLUTIONS/EXAMTIME.java
  SOLUTIONS/EZSPEAK.java
  SOLUTIONS/FARAWAY.java
  SOLUTIONS/FINDSHOES.java
  SOLUTIONS/FIRSTANDLAST.java
  SOLUTIONS/FLIPSORT.java
  SOLUTIONS/FLOORS.java
  SOLUTIONS/FLOW005.java
  SOLUTIONS/FLOW007.java
  SOLUTIONS/FLOW010.java
  SOLUTIONS/FLOW014.java
  SOLUTIONS/FLOW016.java
Labels: Hacktoberfest, HACKTOBERFEST-ACCEPTED, great-job

#47 Exceptional Handling in Java
  PROBLEMS/Exceptional_handeling.java
Labels: Hacktoberfest

#55 feat: change readme
  README.md
Labels: documentation, good first issue, great-job

#61 Created Searching_Algos_in_JAVA
  PROBLEMS/Searching_Algorithms_in_JAVA.md
Labels: Hacktoberfest, HACKTOBERFEST-ACCEPTED, great-job

#62 Create SelectionSort.java
  DataStructures/SortingAlgorithms/SelectionSort.java
Labels: Hacktoberfest, HACKTOBERFEST-ACCEPTED, great-job

#64 Create Multi_Threading.java
  SOLUTIONS/Multi_Threading.java
Labels: good first issue, Hacktoberfest, HACKTOBERFEST-ACCEPTED, great-job

#65 DSA-roadmap and tutorials
  DSA-RoadmapAndTutorials/RoadMap
  DSA-RoadmapAndTutorials/Tutorials
Labels: documentation, good first issue, Hacktoberfest, non code contribution, HACKTOBERFEST-ACCEPTED, great-job

#74 Added basic java codes
  CODE_OF_CONDUCT.md
  PROBLEMS/java-basic-codes.md
  SOLUTIONS/AreaofRhombus.java
  SOLUTIONS/Areaofcircle.java
  SOLUTIONS/Areaofrect.java
  SOLUTIONS/Areaoftraingle.java
  SOLUTIONS/CurvSurfacArea.java
  SOLUTIONS/EquilateralTraingle.java
  SOLUTIONS/Isosceles.java
  SOLUTIONS/Parallelogram.java
  SOLUTIONS/PerimeterofRhombus.java
  SOLUTIONS/PeriofRec.java
  SOLUTIONS/PeriofRhombus.java
  SOLUTIONS/PeriofSqur.java
  SOLUTIONS/TotalSurAreOfCube.java
  SOLUTIONS/VolOfCon.java
  SOLUTIONS/VolOfPyramid.java
  SOLUTIONS/VolumeOfCylinder.java
  SOLUTIONS/Volumeofcone.java
  SOLUTIONS/periofEqui.java
  SOLUTIONS/periofParall.java
  SOLUTIONS/periofcir.java
Labels: Hacktoberfest, HACKTOBERFEST-ACCEPTED, great-job

#71 bit manipulation module added
  DataStructures/BitManipulation/BINARY_TO_DECIMAL.JAVA
  DataStructures/BitManipulation/DECIMAL_TO_BINARY.JAVA
Labels: good first issue, Hacktoberfest, HACKTOBERFEST-ACCEPTED

#63 Create Grid Unique Paths
  DataStructures/Grid Unique Paths
Labels: good first issue, Hacktoberfest

#11 Create Maximum trains for which stoppage can be provided.java
  SOLUTIONS/Maximum trains for which stoppage can be provided.java
Labels: Hacktoberfest, HACKTOBERFEST-ACCEPTED, great-job

#75 Added Java-Bootcamp tutorials & assignments
  DSA-RoadmapAndTutorials/Tutorials
  DSA-RoadmapAndTutorials/assignments/1-flow-of-program.md
  DSA-RoadmapAndTutorials/assignments/2-first-java.md
  DSA-RoadmapAndTutorials/assignments/3-conditionals-loops.md
  DSA-RoadmapAndTutorials/assignments/4-functions.md
  DSA-RoadmapAndTutorials/assignments/5-arrays.md
  DSA-RoadmapAndTutorials/assignments/6-searching.md
  DSA-RoadmapAndTutorials/assignments/7-sorting.md
  DSA-RoadmapAndTutorials/assignments/patterns.md
Labels: documentation, good first issue, Hacktoberfest, non code contribution, HACKTOBERFEST-ACCEPTED, great-job

#76 Added Cyclic Sort ALgotrithm
  DataStructures/SortingAlgorithms/cyclicSort.class
  DataStructures/SortingAlgorithms/cyclicSort.java
Labels: good first issue, Hacktoberfest, HACKTOBERFEST-ACCEPTED, great-job

#82 Tic_Tac_Toe game in java
  SIMPLE PROJECTS/Tic-Tac-Toe.java
Labels: Hacktoberfest, HACKTOBERFEST-ACCEPTED, great-job

#83 Added Binary Search in a new folder
  DataStructures/SearchingAlgorithms/BinarySearch.java
  DataStructures/SearchingAlgorithms/binarySearch.class
Labels: good first issue, Hacktoberfest, HACKTOBERFEST-ACCEPTED, great-job

#84 Added Doubly Linked List
  DataStructures/CircularLinkedList.class
  DataStructures/DoublyLinkedList.class
  DataStructures/DoublyLinkedList.java
Labels: good first issue, Hacktoberfest, HACKTOBERFEST-ACCEPTED, great-job

#91 Java Exceptions Explained.java
  PROBLEMS/Exception Handling/Java Exceptions Explained.java
Labels: good first issue, Hacktoberfest, HACKTOBERFEST-ACCEPTED

#92 Added Shell Sort
  DataStructures/SortingAlgorithms/ShellSort.class
  DataStructures/SortingAlgorithms/shellSort.java
Labels: good first issue, Hacktoberfest, HACKTOBERFEST-ACCEPTED

#93 Polymorphism Explained
  PROBLEMS/Polymorphism/Polymorphism Explained.java
Labels: good first issue, Hacktoberfest, HACKTOBERFEST-ACCEPTED, great-job

#95 Update Tutorials
  DSA-RoadmapAndTutorials/Tutorials
Labels: documentation, good first issue, non code contribution

#42 Kadane Algorithm to find Maximum SubArray Sum
  .DS_Store
  DataStructures/Kadane_Algo.java
  SIMPLE PROJECTS/.DS_Store
Labels: good first issue, Hacktoberfest, HACKTOBERFEST-ACCEPTED, great-job

#103 Add a recursion folder
  DataStructures/Recursion/Leetcode/count_opearation_zero.java
  DataStructures/Recursion/Leetcode/make_it_zero.java
  DataStructures/Recursion/understand/Main.java
  DataStructures/Recursion/understand/binary_search.java
  DataStructures/Recursion/understand/concept.java
  DataStructures/Recursion/understand/print_number.java
  DataStructures/Recursion/understand/sum_digits.java
Labels: good first issue, Hacktoberfest, great-job

#102 Added rock paper scissors game
  SIMPLE PROJECTS/Rockpaperscissors.java
Labels: good first issue, Hacktoberfest, great-job

#100 Create OccurenceOfCharInString.java
  SOLUTIONS/OccurenceOfCharInString.java
Labels: good first issue, Hacktoberfest, HACKTOBERFEST-ACCEPTED, great-job

#99 Binary Tree Implementaion Code- Added
  DataStructures/BinaryTree.java
Labels: good first issue, Hacktoberfest, HACKTOBERFEST-ACCEPTED

#98 Fenixhub/matrices
  SIMPLE PROJECTS/Linear Algebra/matrix-lib/.gitignore
  SIMPLE PROJECTS/Linear Algebra/matrix-lib/README.md
  SIMPLE PROJECTS/Linear Algebra/matrix-lib/jmatrix_classes.svg
  SIMPLE PROJECTS/Linear Algebra/matrix-lib/pom.xml
  SIMPLE PROJECTS/Linear Algebra/matrix-lib/src/main/java/com/fenixhub/App.java
  SIMPLE PROJECTS/Linear Algebra/matrix-lib/src/main/java/com/fenixhub/exceptions/MatrixException.java
  SIMPLE PROJECTS/Linear Algebra/matrix-lib/src/main/java/com/fenixhub/exceptions/MatrixOperationException.java
  SIMPLE PROJECTS/Linear Algebra/matrix-lib/src/main/java/com/fenixhub/exceptions/MatrixSizeException.java
  SIMPLE PROJECTS/Linear Algebra/matrix-lib/src/main/java/com/fenixhub/matrix/builders/GenericMatrixBuilder.java
  SIMPLE PROJECTS/Linear Algebra/matrix-lib/src/main/java/com/fenixhub/matrix/classes/AbstractGenericMatrix.java
  SIMPLE PROJECTS/Linear Algebra/matrix-lib/src/main/java/com/fenixhub/matrix/classes/DoubleMatrix.java
  SIMPLE PROJECTS/Linear Algebra/matrix-lib/src/main/java/com/fenixhub/matrix/classes/FloatMatrix.java
  SIMPLE PROJECTS/Linear Algebra/matrix-lib/src/main/java/com/fenixhub/matrix/classes/GenericMatrix.java
  SIMPLE PROJECTS/Linear Algebra/matrix-lib/src/main/java/com/fenixhub/matrix/classes/IntegerMatrix.java
  SIMPLE PROJECTS/Linear Algebra/matrix-lib/src/main/java/com/fenixhub/matrix/classes/LongMatrix.java
  SIMPLE PROJECTS/Linear Algebra/matrix-lib/src/main/java/com/fenixhub/matrix/classes/ShortMatrix.java
  SIMPLE PROJECTS/Linear Algebra/matrix-lib/src/main/java/com/fenixhub/matrix/utilities/MatrixOperations.java
  SIMPLE PROJECTS/Linear Algebra/matrix-lib/src/test/java/com/fenixhub/AppTest.java
Labels: Hacktoberfest, HACKTOBERFEST-ACCEPTED, great-job

#105 BFS to check graph is bipartite or not
  DataStructures/Bipartite_BSF.cpp
Labels: good first issue, Hacktoberfest, HACKTOBERFEST-ACCEPTED

#106 DFS to check graph is bipartite or not
  DataStructures/DFS_bipartite.cpp
Labels: good first issue, Hacktoberfest, HACKTOBERFEST-ACCEPTED

#107 Login form
  SIMPLE PROJECTS/Login-Form/SIMPLE/userpass.java
Labels: good first issue, Hacktoberfest, HACKTOBERFEST-ACCEPTED

#111 Create RadixSort.java
  DataStructures/SortingAlgorithms/RadixSort.java
Labels: good first issue, Hacktoberfest, HACKTOBERFEST-ACCEPTED

#112 Add Prime Checker with input number and Alphabet Pattern
  .idea/.gitignore
  .idea/Defeat-JAVA.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  SIMPLE PROJECTS/Beginner Java/AlphabetPattern.java
  SIMPLE PROJECTS/Beginner Java/PrimeNumberWithScannerInput.java
  SIMPLE PROJECTS/SpringAppsWithMongoDB/.gitignore
  SIMPLE PROJECTS/SpringAppsWithMongoDB/.mvn/wrapper/maven-wrapper.jar
  SIMPLE PROJECTS/SpringAppsWithMongoDB/.mvn/wrapper/maven-wrapper.properties
  SIMPLE PROJECTS/SpringAppsWithMongoDB/mvnw
  SIMPLE PROJECTS/SpringAppsWithMongoDB/mvnw.cmd
  SIMPLE PROJECTS/SpringAppsWithMongoDB/pom.xml
  SIMPLE PROJECTS/SpringAppsWithMongoDB/src/main/java/com/demo/license/service/LicenseServiceApplication.java
  SIMPLE PROJECTS/SpringAppsWithMongoDB/src/main/java/com/demo/license/service/controller/LicenseController.java
  SIMPLE PROJECTS/SpringAppsWithMongoDB/src/main/java/com/demo/license/service/dao/LicenseDao.java
  SIMPLE PROJECTS/SpringAppsWithMongoDB/src/main/java/com/demo/license/service/dto/ResourceNotFoundException.java
  SIMPLE PROJECTS/SpringAppsWithMongoDB/src/main/java/com/demo/license/service/dto/ResponseLicense.java
  SIMPLE PROJECTS/SpringAppsWithMongoDB/src/main/java/com/demo/license/service/model/License.java
  SIMPLE PROJECTS/SpringAppsWithMongoDB/src/main/java/com/demo/license/service/model/Status.java
  SIMPLE PROJECTS/SpringAppsWithMongoDB/src/main/java/com/demo/license/service/repository/CustomLicenseRepository.java
  SIMPLE PROJECTS/SpringAppsWithMongoDB/src/main/java/com/demo/license/service/repository/CustomLicenseRepositoryImpl.java
  SIMPLE PROJECTS/SpringAppsWithMongoDB/src/main/java/com/demo/license/service/repository/LicenseRepository.java
  SIMPLE PROJECTS/SpringAppsWithMongoDB/src/main/resources/application.properties
  SIMPLE PROJECTS/SpringAppsWithMongoDB/src/test/java/com/demo/license/service/LicenseDaoApplicationTests.java
Labels: Hacktoberfest, HACKTOBERFEST-ACCEPTED, great-job

#113 Add files via upload
  Circular Linked List/CircularLL.java
Labels: Hacktoberfest, HACKTOBERFEST-ACCEPTED, great-job

#116 Added Inheritance and Polymorphism Examples in OOPs dir.
  OOPs/Inheritance/Cuboid.java
  OOPs/Inheritance/Main.java
  OOPs/Inheritance/Rectangle.java
  OOPs/Polymorphism/Car.java
  OOPs/Polymorphism/Mitsubishi.java
  OOPs/Polymorphism/PolyMain.java
Labels: Hacktoberfest, HACKTOBERFEST-ACCEPTED

#114 Return array of indices of an element in array
  DataStructures/Recursion/understand/Return array of indices of an element in array
Labels: good first issue, Hacktoberfest, HACKTOBERFEST-ACCEPTED

#117 Add files via upload
  Binary Tree/BST/BSTTree.java
  Binary Tree/BinaryTree.java
  Binary Tree/BoundaryTraversal.java
  Binary Tree/avgOfNodes.java
  Binary Tree/countOfNodes.java
  Binary Tree/createTree.java
  Binary Tree/diameterOfTree.java
  Binary Tree/diameterOfTree2.java
  Binary Tree/heightOfTree.java
  Binary Tree/sumOfNodes.java
Labels: Hacktoberfest, HACKTOBERFEST-ACCEPTED, great-job

#128 Basic Java Files
  AttendanceGenerator.java
  Publisher.java
  Quantitysort.java
Labels: good first issue, Hacktoberfest, HACKTOBERFEST-ACCEPTED

#127 Basic Java Porgrams of Object and Classes
  Object &Classes/Bike.java
  Object &Classes/Cat.java
  Object &Classes/SimpleClass.java
  Object &Classes/SimpleObject.java
  Object &Classes/Student.java
  Object &Classes/Test.java
Labels: good first issue, Hacktoberfest, HACKTOBERFEST-ACCEPTED, great-job

#130 Create OddEvenSort.java
  DataStructures/SortingAlgorithms/OddEvenSort.java
Labels: good first issue, Hacktoberfest, HACKTOBERFEST-ACCEPTED, great-job

#131 Create BinaryInsertionSort.java
  DataStructures/SortingAlgorithms/BinaryInsertionSort.java
Labels: good first issue, Hacktoberfest, HACKTOBERFEST-ACCEPTED, great-job

#143 Add Trie Dictionary implementation in Java
  DataStructures/TrieDictionary/Dictionary.java
  DataStructures/TrieDictionary/Main.java
  DataStructures/TrieDictionary/Node.java
Labels: Hacktoberfest, HACKTOBERFEST-ACCEPTED, great-job

#135 feat : add scramblies for array in java(hacktoberfest)
  SOLUTIONS/scramblies.java
  SOLUTIONS/split et regex.txt
Labels: Hacktoberfest, HACKTOBERFEST-ACCEPTED, great-job

#134 Added cache project (HacktoberFest)
  SIMPLE PROJECTS/Cache/Cache Project.pdf
  SIMPLE PROJECTS/Cache/FinalSolution.pdf
  SIMPLE PROJECTS/Cache/README.md
  SIMPLE PROJECTS/Cache/src/Associative.java
  SIMPLE PROJECTS/Cache/src/Data.java
  SIMPLE PROJECTS/Cache/src/DataPacket.java
  SIMPLE PROJECTS/Cache/src/Direct.java
  SIMPLE PROJECTS/Cache/src/Main.java
  SIMPLE PROJECTS/Cache/src/Reader.java
  SIMPLE PROJECTS/Cache/src/Set.java
Labels: Hacktoberfest, HACKTOBERFEST-ACCEPTED, great-job
